### ISSUE TITLE
Suggestion: an option for keeping cursor position after undoing

### ISSUE THREAD

**Issue by auwsmit** [joereynolds/place.vim#6]
So, currently, if I do something like `ga$;` and then I decide to undo that, then my cursor is moved to the last undone change. Not a big deal, but somewhat unexpected when the plugin typically doesn't move the cursor.

I don't know if it should be default or not, but I think an option would be good either way (if possible).

**Comment by joereynolds** [comment]
Hey @auwsmit,

Thanks for bringing that to my attention, it's on the list!

**Comment by joereynolds** [comment]
Hey @auwsmit,

I've got this working for most of the motions, let me know if there are any issues.
Thanks!

https://github.com/joereynolds/place.vim/commit/3661ec412b8a2d73f3d398c8defbb222ea2372ed
