### ISSUE TITLE
Separate mapping for multiple-character mode

### ISSUE THREAD

**Issue by willdurney** [joereynolds/place.vim#7]
Great plugin! It would be useful to me to be able to have two separate mappings for place-single and place-multiple. Right now it seems the only way to switch between modes is by toggling that variable.

**Comment by joereynolds** [comment]
Hey @futurityverb 

How's this?
https://github.com/joereynolds/place.vim/commit/04efe574f0767b03dd08ec4d7e50e35872221c64

Thanks!

**Comment by willdurney** [comment]
Works perfectly, thanks!
