### ISSUE TITLE
F and T aren't supported

### ISSUE THREAD

**Issue by shtanton** [joereynolds/place.vim#8]
Lowercase f and t for searching forward are supported but going backwards with F and T is not.
I would guess that adding this isn't very different from the forward search so I am happy to make a PR for it if you need me too.

Keep up the good work :)

**Comment by joereynolds** [comment]
Hey @shtanton,

This has been added, let me know if there are any issues.
Thanks!

https://github.com/joereynolds/place.vim/commit/d1fc2abe7c8cdbfcd78bb284973ae3b4a99dd744
